"""Build the restricted Speex decoder and its independent upstream reference."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tarfile
import urllib.request

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
URL='https://downloads.xiph.org/releases/speex/speex-1.2.1.tar.gz'
SHA='4b44d4f2b38a370a2d98a78329fefc56a0cf93d1c1be70029217baae6628feea'
SOURCES='cb_search exc_10_32_table exc_8_128_table filters gain_table hexc_table high_lsp_tables lsp ltp speex stereo vbr vq bits exc_10_16_table exc_20_32_table exc_5_256_table exc_5_64_table gain_table_lbr hexc_10_32_table lpc lsp_tables_nb modes modes_wb nb_celp quant_lsp sb_celp speex_callbacks speex_header window'.split()

def run(args,log,cwd):
    env=os.environ.copy()
    env['PATH']=str(Path(args[0]).parent)+os.pathsep+env['PATH']
    p=subprocess.run(args,cwd=cwd,env=env,capture_output=True,text=True,errors='replace')
    log.write_text(p.stdout+p.stderr,encoding='utf-8')
    if p.returncode: raise RuntimeError(f'{args[0]} failed: {log}\n'+(p.stdout+p.stderr)[-2500:])

def vendor(source):
    tables=[]
    for file,names in [('lsp_tables_nb.c',['cdbk_nb','cdbk_nb_low1','cdbk_nb_high1']),
                       ('gain_table_lbr.c',['gain_cdbk_lbr']),('exc_10_32_table.c',['exc_10_32_table']),
                       ('nb_celp.c',['ol_gain_table'])]:
        text=(source/'libspeex'/file).read_text()
        for name in names:
            m=re.search(r'(?:static )?const (?:signed char|spx_word32_t) '+name+r'\[[^]]*\]\s*=\s*\{[^}]*\};',text,re.S)
            assert m,name
            tables.append(m[0].replace('spx_word32_t','s32').replace('static const','const'))
    data='/* From Speex 1.2.1, Xiph.Org. See LICENSE.speex. Generated by build.py. */\n'+'\n'.join(tables)+'\n'
    data='\n'.join(line.rstrip() for line in data.split('\n'))
    (HERE/'tables.h').write_text(data,encoding='utf-8',newline='\n')
    (HERE/'LICENSE.speex').write_text((source/'COPYING').read_text(),encoding='utf-8',newline='\n')

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output',type=Path,default=ROOT/'build/speex-port')
    p.add_argument('--sdcc',type=Path,default=Path('C:/Work/ZX-video/.tmp/z80-c-compilers/sdcc/bin/sdcc.exe'))
    p.add_argument('--vcvars',type=Path,default=Path('C:/Program Files/Microsoft Visual Studio/18/Community/VC/Auxiliary/Build/vcvars64.bat'))
    p.add_argument('--host-only',action='store_true')
    p.add_argument('--variant',choices=['z80','asm','table','pure-asm','pure-fast','pure-r1','pure-r2','pure-r3-register','pure-r3','pure-r4','pure-r7','pure-r8','pure-r9','pure-r10-approx'],default='pure-r4')
    p.add_argument('--skip-host',action='store_true')
    a=p.parse_args();out=a.output.resolve();out.mkdir(parents=True,exist_ok=True)
    source=out/'speex-1.2.1'
    if not a.skip_host:
        archive=out/'speex-1.2.1.tar.gz'
        if not archive.exists(): archive.write_bytes(urllib.request.urlopen(URL,timeout=60).read())
        assert hashlib.sha256(archive.read_bytes()).hexdigest()==SHA,'Source archive hash mismatch'
        if not source.exists():
            with tarfile.open(archive) as tar: tar.extractall(out,filter='data')
        vendor(source)
    (out/'source.json').write_text(json.dumps(dict(url=URL,sha256=SHA,version='1.2.1'),indent=2)+'\n')
    if a.variant.startswith('pure-') and not a.host_only:
        from make_decoder import emit
        target=out/a.variant;target.mkdir(exist_ok=True)
        emit(target/'decoder.s',fast=a.variant!='pure-asm')
        if a.variant.startswith('pure-r'):
            from optimize import optimize
            optimize(target,'pure-r4' if a.variant in ('pure-r7','pure-r8','pure-r9','pure-r10-approx') else a.variant)
            if a.variant in ('pure-r7','pure-r8','pure-r9','pure-r10-approx'):
                from followup_opt import apply
                apply(target,a.variant)
        for name in ('decoder','filter'):
            run([str(a.sdcc.with_name('sdasz80.exe')),'-plosgff',name+'.rel',name+'.s'],target/(name+'-asm.log'),target)
        run([str(a.sdcc),'-mz80','--no-std-crt0','--code-loc','0x8000','--data-loc','0xb000','decoder.rel','filter.rel','-o','player.ihx'],target/'link.log',target)
        if a.skip_host:
            print(target)
            return
    ref=out/'host';ref.mkdir(exist_ok=True)
    cmd='@echo off\ncall "'+str(a.vcvars)+'" >nul\nif errorlevel 1 exit /b 1\n'
    cmd+='cl /nologo /O2 /LD /DFIXED_POINT /DUSE_ALLOCA /DEXPORT= /D_CRT_SECURE_NO_WARNINGS /I"'+str(source/'include')+'" /I"'+str(source/'libspeex')+'" '
    cmd+=' '.join('"'+str(source/'libspeex'/(name+'.c'))+'"' for name in SOURCES)
    cmd+=' "'+str(HERE/'reference.c')+'" /Fe:reference.dll\nif errorlevel 1 exit /b 1\n'
    cmd+='cl /nologo /O2 /LD "'+str(HERE/'decoder.c')+'" /Fe:decoder.dll\nexit /b %errorlevel%\n'
    (ref/'build.cmd').write_text(cmd)
    if not a.skip_host:run(['cmd','/c',str(ref/'build.cmd')],ref/'build.log',ref)
    if not a.host_only and not a.variant.startswith('pure-'):
        target=out/a.variant;target.mkdir(exist_ok=True)
        flags=['-mz80','--std-c99','--opt-code-speed','--max-allocs-per-node','10000']
        if a.variant!='z80':flags+=['-DASM_FILTER']
        for name in ('decoder','player'):
            run([str(a.sdcc),*flags,'-I'+str(HERE),'-c',str(HERE/(name+'.c')),'-o',name+'.rel'],target/(name+'-build.log'),target)
        extra=[]
        if a.variant!='z80':
            from make_asm import generate
            generate(target/'filter.s',table=a.variant=='table')
            run([str(a.sdcc.with_name('sdasz80.exe')),'-plosgff','filter.rel','filter.s'],target/'asm.log',target)
            extra=['filter.rel']
        run([str(a.sdcc),'-mz80','--no-std-crt0','--code-loc','0x8000','--data-loc','0xb000','decoder.rel','player.rel',*extra,'-o','player.ihx'],target/'link.log',target)
    (out/'source.json').write_text(json.dumps(dict(url=URL,sha256=SHA,version='1.2.1'),indent=2)+'\n')
    print(out)

if __name__=='__main__':main()
