"""Generate unrolled Z80 synthesis and an exact 1024-byte quarter-square LUT."""
from pathlib import Path

def generate(path,table=False,fast=False):
    mul='_zx_mul_table' if table else '___mulsint2slong'
    text='''; Generated by make_asm.py; exact Speex synthesis, no PDM.
    .module speex_filter
    .globl _zx_speex_filter, _zx_lpc, _zx_memory, _zx_clip
    .globl ___mulsint2slong, _zx_mul_table, _zx_mul8
    .area _DATA
asm_n: .ds 2
asm_y: .ds 2
asm_count: .ds 1
mul_a: .ds 2
mul_b: .ds 2
mul_sign: .ds 1
mul_result: .ds 4
    .area _CODE
_zx_speex_filter::
    push ix
    push iy
    push hl
    pop ix
    push de
    pop iy
    ld a,#40
    ld (asm_count),a
filter_sample:
    ld hl,(_zx_memory)
    ld bc,#4096
    add hl,bc
    ld de,(_zx_memory+2)
    jr nc,round_no_carry
    inc de
round_no_carry:
    ; Signed 32-bit >>13: discard eight bits, then shift the remaining 24 five times.
    ld l,h
    ld h,e
    ld e,d
'''
    text+='    sra e\n    rr h\n    rr l\n'*5
    text+='''    ld c,0(ix)
    ld b,1(ix)
    ld a,b
    add a,a
    sbc a,a
    add hl,bc
    adc a,e
    ld e,a
    add a,a
    sbc a,a
    ld d,a
    ex de,hl
    call _zx_clip
    ld (asm_y),de
    ld 0(iy),e
    ld 1(iy),d
    inc ix
    inc ix
    inc iy
    inc iy
    xor a,a
    sub a,e
    ld l,a
    sbc a,a
    sub a,d
    ld h,a
    ld (asm_n),hl
    push iy
'''
    for i in range(10):
        text+=f'    ld hl,(_zx_lpc+{2*i})\n    ld de,(asm_n)\n    call {mul}\n'
        if i<9:
            text+=f'''    ld bc,(_zx_memory+{4*i+4})
    ex de,hl
    add hl,bc
    ex de,hl
    ld bc,(_zx_memory+{4*i+6})
    adc hl,bc
'''
        text+=f'    ld (_zx_memory+{4*i}),de\n    ld (_zx_memory+{4*i+2}),hl\n'
    text+='''    pop iy
    ld hl,#asm_count
    dec (hl)
    jp nz,filter_sample
    pop iy
    pop ix
    ret

; Exact signed HL * DE -> HL:DE, SDCC call(1) ABI. Not reentrant.
_zx_mul_table::
    ld a,h
    xor a,d
    and a,#128
    ld (mul_sign),a
    bit 7,h
    jr z,mul_a_positive
    xor a,a
    sub a,l
    ld l,a
    sbc a,a
    sub a,h
    ld h,a
mul_a_positive:
    bit 7,d
    jr z,mul_b_positive
    xor a,a
    sub a,e
    ld e,a
    sbc a,a
    sub a,d
    ld d,a
mul_b_positive:
    ld (mul_a),hl
    ld (mul_b),de
    ld a,l
    ld c,e
    call _zx_mul8
    ld (mul_result),hl
    ld a,(mul_b+1)
    ld c,a
    ld a,(mul_a+1)
    call _zx_mul8
    ld (mul_result+2),hl
    ld a,(mul_b+1)
    ld c,a
    ld a,(mul_a)
    call _zx_mul8
    call add_cross
    ld a,(mul_b)
    ld c,a
    ld a,(mul_a+1)
    call _zx_mul8
    call add_cross
    ld de,(mul_result)
    ld hl,(mul_result+2)
    ld a,(mul_sign)
    or a,a
    ret z
    xor a,a
    sub a,e
    ld e,a
    ld a,#0
    sbc a,d
    ld d,a
    ld a,#0
    sbc a,l
    ld l,a
    ld a,#0
    sbc a,h
    ld h,a
    ret
add_cross:
    ld a,(mul_result+1)
    add a,l
    ld (mul_result+1),a
    ld a,(mul_result+2)
    adc a,h
    ld (mul_result+2),a
    ret nc
    ld hl,#mul_result+3
    inc (hl)
    ret

; Unsigned A*C -> HL, destroys AF/BC/DE. Q(n)=floor(n*n/4).
; Q(a+b)-Q(abs(a-b)) is exact because sum and difference have equal parity.
_zx_mul8::
    ld b,a
    add a,c
    ld l,a
    ld a,#0x60
    adc a,#0
    ld h,a
    ld e,(hl)
    inc h
    inc h
    ld d,(hl)
    ld a,b
    sub a,c
    jr nc,diff_positive
    neg
diff_positive:
    ld l,a
    ld h,#0x60
    ld a,(hl)
    inc h
    inc h
    ld h,(hl)
    ld l,a
    ex de,hl
    or a,a
    sbc hl,de
    ret
    .area _QTABLE (ABS)
    .org 0x6000
'''
    if fast:
        text=text.replace('_zx_mul_table::\n', '''_zx_mul_table::
    ld a,h
    or a,l
    jr z,mul_zero
    ld a,d
    or a,e
    jr nz,mul_nonzero
mul_zero:
    ld hl,#0
    ld de,#0
    ret
mul_nonzero:
''')
        text=text.replace('    ld (mul_result),hl\n    ld a,(mul_b+1)', '''    ld (mul_result),hl
    ld a,(mul_a+1)
    or a,a
    jr z,mul_a_byte
    ld a,(mul_b+1)
    or a,a
    jr z,mul_b_byte
    ld a,(mul_b+1)''')
        text=text.replace('    ld de,(mul_result)\n', 'mul_finish:\n    ld de,(mul_result)\n')
        text=text.replace('add_cross:\n','''mul_a_byte:
    ld hl,#0
    ld (mul_result+2),hl
    ld a,(mul_b+1)
    or a,a
    jr z,mul_finish
    ld c,a
    ld a,(mul_a)
    call _zx_mul8
    call add_cross
    jr mul_finish
mul_b_byte:
    ld hl,#0
    ld (mul_result+2),hl
    ld a,(mul_b)
    ld c,a
    ld a,(mul_a+1)
    call _zx_mul8
    call add_cross
    jr mul_finish
add_cross:
''')
    q=[n*n//4 for n in range(512)]
    data=[n&255 for n in q]+[n>>8 for n in q]
    for i in range(0,len(data),16):text+='    .db '+','.join(str(n) for n in data[i:i+16])+'\n'
    path.write_text(text,encoding='utf-8',newline='\n')
