; Generated by make_asm.py; exact Speex synthesis, no PDM.
    .module speex_filter
.globl _prepare_coefficients, _split_nibbles, _coefficient_product
    .globl _zx_speex_filter, _zx_lpc, _zx_memory, _zx_clip
    .globl _zx_mul_table, _zx_mul8
    .area _DATA
asm_y: .ds 2
asm_count: .ds 1
mul_a: .ds 2
mul_b: .ds 2
mul_sign: .ds 1
mul_result: .ds 4
    .area _CODE
; HL excitation input; 40 samples to PCM8 OUT, no PCM16 output buffer.
; Internal PCM16 feedback is retained; _last_pcm16 exposes it to verification.
; Preserves IX/IY; ordinary and alternate AF/BC/DE/HL and scratch are clobbered.
_zx_speex_filter::
    push ix
    push iy
    push hl
    ld a,#40
    ld (asm_count),a
    call _prepare_coefficients
; Preparation clobbers both register sets. Recover the saved input cursor only
; afterwards; alternate HL remains its cursor throughout this 40-sample call.
    exx
    pop hl
    exx
filter_sample:
    ld hl,(_zx_memory)
    ld bc,#4096
    add hl,bc
    ld de,(_zx_memory+2)
    jr nc,round_no_carry
    inc de
round_no_carry:
    ; Signed 32-bit >>13: discard eight bits, then shift the remaining 24 five times.
    ld l,h
    ld h,e
    ld e,d
    sra e
    rr h
    rr l
    sra e
    rr h
    rr l
    sra e
    rr h
    rr l
    sra e
    rr h
    rr l
    sra e
    rr h
    rr l
; Fetch through the alternate cursor and transfer its word via the real stack.
; _zx_clip and the inline product/state update preserve alternate HL.
    exx
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    push bc
    exx
    pop bc
    ld a,b
    add a,a
    sbc a,a
    add hl,bc
    adc a,e
    ld e,a
    add a,a
    sbc a,a
    ld d,a
    ex de,hl
    call _zx_clip
    ld (asm_y),de
    xor a,a
    sub a,e
    ld l,a
    sbc a,a
    sub a,d
    ld h,a
; A still equals H after the signed negation, so this test needs only OR L.
; Feedback n=-y in HL: a zero product shifts the following nine 32-bit states
; and clears the final state, even when earlier history is nonzero.
.globl _filter_feedback_start, _filter_emit
_filter_feedback_start::
    or a,l
    jp z,filter_zero_feedback
; Split signed feedback once into IX/IY halves. Indexed LD A,r followed
; by ordinary LD L,A intentionally avoids DD/FD substitution of ordinary L.
; Every inline product leaves exact modulo32 BC:DE, including signed top nibble.
ld a,l
and a,#15
add a,a
add a,a
.db 0xdd,0x6f ; LD IXL,A: 8 T
ld a,l
and a,#240
rrca
rrca
or a,#64
.db 0xdd,0x67 ; LD IXH,A: 8 T
ld a,h
and a,#15
add a,a
add a,a
or a,#129
.db 0xfd,0x6f ; LD IYL,A: 8 T
ld a,h
and a,#240
rrca
rrca
or a,#193
.db 0xfd,0x67 ; LD IYH,A: 8 T
; Synthesis tap 0: coefficient page 0x72.
ld h,#114
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+4)
add hl,de
ld (_zx_memory+0),hl
ld hl,(_zx_memory+6)
adc hl,bc
ld (_zx_memory+2),hl
; Synthesis tap 1: coefficient page 0x73.
ld h,#115
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+8)
add hl,de
ld (_zx_memory+4),hl
ld hl,(_zx_memory+10)
adc hl,bc
ld (_zx_memory+6),hl
; Synthesis tap 2: coefficient page 0x74.
ld h,#116
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+12)
add hl,de
ld (_zx_memory+8),hl
ld hl,(_zx_memory+14)
adc hl,bc
ld (_zx_memory+10),hl
; Synthesis tap 3: coefficient page 0x75.
ld h,#117
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+16)
add hl,de
ld (_zx_memory+12),hl
ld hl,(_zx_memory+18)
adc hl,bc
ld (_zx_memory+14),hl
; Synthesis tap 4: coefficient page 0x76.
ld h,#118
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+20)
add hl,de
ld (_zx_memory+16),hl
ld hl,(_zx_memory+22)
adc hl,bc
ld (_zx_memory+18),hl
; Synthesis tap 5: coefficient page 0x77.
ld h,#119
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+24)
add hl,de
ld (_zx_memory+20),hl
ld hl,(_zx_memory+26)
adc hl,bc
ld (_zx_memory+22),hl
; Synthesis tap 6: coefficient page 0x78.
ld h,#120
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+28)
add hl,de
ld (_zx_memory+24),hl
ld hl,(_zx_memory+30)
adc hl,bc
ld (_zx_memory+26),hl
; Synthesis tap 7: coefficient page 0x79.
ld h,#121
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+32)
add hl,de
ld (_zx_memory+28),hl
ld hl,(_zx_memory+34)
adc hl,bc
ld (_zx_memory+30),hl
; Synthesis tap 8: coefficient page 0x7a.
ld h,#122
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld hl,(_zx_memory+36)
add hl,de
ld (_zx_memory+32),hl
ld hl,(_zx_memory+38)
adc hl,bc
ld (_zx_memory+34),hl
; Synthesis tap 9: coefficient page 0x7b.
ld h,#123
.db 0xdd,0x7d ; LD A,IXL: 8 T
ld l,a
ld e,(hl)
inc l
ld d,(hl)
inc l
ld c,(hl)
inc l
ld b,(hl)
.db 0xdd,0x7c ; LD A,IXH: 8 T
ld l,a
ld a,e
add a,(hl)
ld e,a
inc l
ld a,d
adc a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7d ; LD A,IYL: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
; Shifted partial has low byte zero. Offset starts at byte 1;
; E remains unchanged and ADD starts a new carry chain at D.
.db 0xfd,0x7c ; LD A,IYH: 8 T
ld l,a
ld a,d
add a,(hl)
ld d,a
inc l
ld a,c
adc a,(hl)
ld c,a
inc l
ld a,b
adc a,(hl)
ld b,a
ld (_zx_memory+36),de
ld (_zx_memory+38),bc
_filter_emit::
    ld a,(asm_y+1)
    xor a,#128
    out (0xfb),a
    ld hl,#asm_count
    dec (hl)
    jp nz,filter_sample
    pop iy
    pop ix
    ret

; Zero-feedback update; preserves IX/IY and SP, clobbers AF/BC/DE/HL.
; Source is four bytes ahead of destination, so forward LDIR's overlap is safe.
; No coefficient products are used; their cached nibble operands can stay old.
filter_zero_feedback:
    ld hl,#_zx_memory+4
    ld de,#_zx_memory
    ld bc,#36
    ldir
    ld hl,#0
    ld (_zx_memory+36),hl
    ld (_zx_memory+38),hl
    jp _filter_emit

; Exact signed HL * DE -> HL:DE, SDCC call(1) ABI. Not reentrant.
; Exact register-based signed16x16 -> HL:DE, preserving IX/IY.
; BC:HL shifts as a 32-bit accumulator; incoming multiplier bits select adds.
_zx_mul_table::
ld a,h
or a,l
jr z,reg_zero
ld a,d
or a,e
jr nz,reg_nonzero
reg_zero:
ld hl,#0
ld de,#0
ret
reg_nonzero:
ld a,h
xor a,d
and a,#128
ld (mul_sign),a
bit 7,h
jr z,reg_a_positive
xor a,a
sub a,l
ld l,a
sbc a,a
sub a,h
ld h,a
reg_a_positive:
bit 7,d
jr z,reg_b_positive
xor a,a
sub a,e
ld e,a
sbc a,a
sub a,d
ld d,a
reg_b_positive:
ld a,h
or a,a
jr z,reg_byte
ld a,d
or a,a
jr nz,reg_word
ex de,hl
reg_byte:
ld b,l
ld c,#0
ld hl,#0
jp reg_last8
reg_word:
ld b,h
ld c,l
ld hl,#0
add hl,hl
rl c
rl b
jr nc,reg_bit_0
add hl,de
jr nc,reg_bit_0
inc bc
reg_bit_0:
add hl,hl
rl c
rl b
jr nc,reg_bit_1
add hl,de
jr nc,reg_bit_1
inc bc
reg_bit_1:
add hl,hl
rl c
rl b
jr nc,reg_bit_2
add hl,de
jr nc,reg_bit_2
inc bc
reg_bit_2:
add hl,hl
rl c
rl b
jr nc,reg_bit_3
add hl,de
jr nc,reg_bit_3
inc bc
reg_bit_3:
add hl,hl
rl c
rl b
jr nc,reg_bit_4
add hl,de
jr nc,reg_bit_4
inc bc
reg_bit_4:
add hl,hl
rl c
rl b
jr nc,reg_bit_5
add hl,de
jr nc,reg_bit_5
inc bc
reg_bit_5:
add hl,hl
rl c
rl b
jr nc,reg_bit_6
add hl,de
jr nc,reg_bit_6
inc bc
reg_bit_6:
add hl,hl
rl c
rl b
jr nc,reg_bit_7
add hl,de
jr nc,reg_bit_7
inc bc
reg_bit_7:
reg_last8:
add hl,hl
rl c
rl b
jr nc,reg_bit_8
add hl,de
jr nc,reg_bit_8
inc bc
reg_bit_8:
add hl,hl
rl c
rl b
jr nc,reg_bit_9
add hl,de
jr nc,reg_bit_9
inc bc
reg_bit_9:
add hl,hl
rl c
rl b
jr nc,reg_bit_10
add hl,de
jr nc,reg_bit_10
inc bc
reg_bit_10:
add hl,hl
rl c
rl b
jr nc,reg_bit_11
add hl,de
jr nc,reg_bit_11
inc bc
reg_bit_11:
add hl,hl
rl c
rl b
jr nc,reg_bit_12
add hl,de
jr nc,reg_bit_12
inc bc
reg_bit_12:
add hl,hl
rl c
rl b
jr nc,reg_bit_13
add hl,de
jr nc,reg_bit_13
inc bc
reg_bit_13:
add hl,hl
rl c
rl b
jr nc,reg_bit_14
add hl,de
jr nc,reg_bit_14
inc bc
reg_bit_14:
add hl,hl
rl c
rl b
jr nc,reg_bit_15
add hl,de
jr nc,reg_bit_15
inc bc
reg_bit_15:
ex de,hl
ld h,b
ld l,c
ld a,(mul_sign)
or a,a
ret z
xor a,a
sub a,e
ld e,a
ld a,#0
sbc a,d
ld d,a
ld a,#0
sbc a,l
ld l,a
ld a,#0
sbc a,h
ld h,a
ret

; Unsigned A*C -> HL, destroys AF/BC/DE. Q(n)=floor(n*n/4).
; Q(a+b)-Q(abs(a-b)) is exact because sum and difference have equal parity.
_zx_mul8::
    ld b,a
    add a,c
    ld l,a
    ld a,#0x61
    adc a,#0
    ld h,a
    ld e,(hl)
    inc h
    inc h
    ld d,(hl)
    ld a,b
    sub a,c
    jr nc,diff_positive
    neg
diff_positive:
    ld l,a
    ld h,#0x61
    ld a,(hl)
    inc h
    inc h
    ld h,(hl)
    ld l,a
    ex de,hl
    or a,a
    sbc hl,de
    ret
    .area _QTABLE (ABS)
    .org 0x6100
    .db 0,0,1,2,4,6,9,12,16,20,25,30,36,42,49,56
    .db 64,72,81,90,100,110,121,132,144,156,169,182,196,210,225,240
    .db 0,16,33,50,68,86,105,124,144,164,185,206,228,250,17,40
    .db 64,88,113,138,164,190,217,244,16,44,73,102,132,162,193,224
    .db 0,32,65,98,132,166,201,236,16,52,89,126,164,202,241,24
    .db 64,104,145,186,228,14,57,100,144,188,233,22,68,114,161,208
    .db 0,48,97,146,196,246,41,92,144,196,249,46,100,154,209,8
    .db 64,120,177,234,36,94,153,212,16,76,137,198,4,66,129,192
    .db 0,64,129,194,4,70,137,204,16,84,153,222,36,106,177,248
    .db 64,136,209,26,100,174,249,68,144,220,41,118,196,18,97,176
    .db 0,80,161,242,68,150,233,60,144,228,57,142,228,58,145,232
    .db 64,152,241,74,164,254,89,180,16,108,201,38,132,226,65,160
    .db 0,96,193,34,132,230,73,172,16,116,217,62,164,10,113,216
    .db 64,168,17,122,228,78,185,36,144,252,105,214,68,178,33,144
    .db 0,112,225,82,196,54,169,28,144,4,121,238,100,218,81,200
    .db 64,184,49,170,36,158,25,148,16,140,9,134,4,130,1,128
    .db 0,128,1,130,4,134,9,140,16,148,25,158,36,170,49,184
    .db 64,200,81,218,100,238,121,4,144,28,169,54,196,82,225,112
    .db 0,144,33,178,68,214,105,252,144,36,185,78,228,122,17,168
    .db 64,216,113,10,164,62,217,116,16,172,73,230,132,34,193,96
    .db 0,160,65,226,132,38,201,108,16,180,89,254,164,74,241,152
    .db 64,232,145,58,228,142,57,228,144,60,233,150,68,242,161,80
    .db 0,176,97,18,196,118,41,220,144,68,249,174,100,26,209,136
    .db 64,248,177,106,36,222,153,84,16,204,137,70,4,194,129,64
    .db 0,192,129,66,4,198,137,76,16,212,153,94,36,234,177,120
    .db 64,8,209,154,100,46,249,196,144,92,41,246,196,146,97,48
    .db 0,208,161,114,68,22,233,188,144,100,57,14,228,186,145,104
    .db 64,24,241,202,164,126,89,52,16,236,201,166,132,98,65,32
    .db 0,224,193,162,132,102,73,44,16,244,217,190,164,138,113,88
    .db 64,40,17,250,228,206,185,164,144,124,105,86,68,50,33,16
    .db 0,240,225,210,196,182,169,156,144,132,121,110,100,90,81,72
    .db 64,56,49,42,36,30,25,20,16,12,9,6,4,2,1,0
    .db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    .db 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    .db 1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2
    .db 2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3
    .db 4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,6
    .db 6,6,6,6,6,7,7,7,7,7,7,8,8,8,8,8
    .db 9,9,9,9,9,9,10,10,10,10,10,11,11,11,11,12
    .db 12,12,12,12,13,13,13,13,14,14,14,14,15,15,15,15
    .db 16,16,16,16,17,17,17,17,18,18,18,18,19,19,19,19
    .db 20,20,20,21,21,21,21,22,22,22,23,23,23,24,24,24
    .db 25,25,25,25,26,26,26,27,27,27,28,28,28,29,29,29
    .db 30,30,30,31,31,31,32,32,33,33,33,34,34,34,35,35
    .db 36,36,36,37,37,37,38,38,39,39,39,40,40,41,41,41
    .db 42,42,43,43,43,44,44,45,45,45,46,46,47,47,48,48
    .db 49,49,49,50,50,51,51,52,52,53,53,53,54,54,55,55
    .db 56,56,57,57,58,58,59,59,60,60,61,61,62,62,63,63
    .db 64,64,65,65,66,66,67,67,68,68,69,69,70,70,71,71
    .db 72,72,73,73,74,74,75,76,76,77,77,78,78,79,79,80
    .db 81,81,82,82,83,83,84,84,85,86,86,87,87,88,89,89
    .db 90,90,91,92,92,93,93,94,95,95,96,96,97,98,98,99
    .db 100,100,101,101,102,103,103,104,105,105,106,106,107,108,108,109
    .db 110,110,111,112,112,113,114,114,115,116,116,117,118,118,119,120
    .db 121,121,122,123,123,124,125,125,126,127,127,128,129,130,130,131
    .db 132,132,133,134,135,135,136,137,138,138,139,140,141,141,142,143
    .db 144,144,145,146,147,147,148,149,150,150,151,152,153,153,154,155
    .db 156,157,157,158,159,160,160,161,162,163,164,164,165,166,167,168
    .db 169,169,170,171,172,173,173,174,175,176,177,178,178,179,180,181
    .db 182,183,183,184,185,186,187,188,189,189,190,191,192,193,194,195
    .db 196,196,197,198,199,200,201,202,203,203,204,205,206,207,208,209
    .db 210,211,212,212,213,214,215,216,217,218,219,220,221,222,223,224
    .db 225,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239
    .db 240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255

.globl _last_pcm16
_last_pcm16 = asm_y

; Playback never calls the retained standalone self-modifying product helpers.
; Verification must forbid every code write for this entry-to-completion path.
.globl _immutable_playback_code
_immutable_playback_code = 1
